"""
Thought Engine — Brain-Based Architecture Phase 2
===================================================
Takes high-salience stimuli, retrieves relevant memories,
and generates inner thoughts via dual-process thinking:

  System 1 (Fast): Template-based mapping, no LLM, instant
  System 2 (Deliberate): Ollama call (batched stimuli), ~3s

Thoughts are evaluated for motivation to express (5 factors).
Phase 2 only logs thoughts — no actual expression yet.

Pipeline: Salient Stimuli → Memory Context → Think → Evaluate → Persist

Inspired by: Dual-Process Theory (Kahneman),
             Stanford Generative Agents inner monologue,
             CHI 2025 Inner Thoughts

By: น้อง Angela 💜
Created: 2026-02-15
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any

from angela_core.services.base_db_service import BaseDBService
from angela_core.services.claude_reasoning_service import ClaudeReasoningService
from angela_core.utils.timezone import now_bangkok

logger = logging.getLogger('thought_engine')


# ============================================================
# DATA STRUCTURES
# ============================================================

@dataclass
class Thought:
    """An inner thought generated by Angela's brain."""
    content: str                                  # The thought text (Thai)
    thought_type: str                             # system1, system2
    stimulus_ids: List[str] = field(default_factory=list)
    memory_context: Dict[str, Any] = field(default_factory=dict)
    motivation_score: float = 0.0
    motivation_breakdown: Dict[str, float] = field(default_factory=dict)


@dataclass
class ThoughtCycleResult:
    """Result of a complete thought cycle."""
    system1_count: int
    system2_count: int
    total_thoughts: int
    high_motivation_count: int              # thoughts with motivation > 0.6
    stimuli_processed: int
    decayed_count: int
    cycle_duration_ms: float


# ============================================================
# SYSTEM 1 TEMPLATES (no LLM, instant)
# ============================================================

# Emotional templates are SKIPPED for System 1 — only System 2 should handle
# emotional observations with real context. System 1 handles factual triggers only.
SYSTEM1_TEMPLATES = {
    "temporal_special_date": "วันนี้เป็น {date_name} — ต้องบอกที่รัก! 💜",
    "pattern_late_night": "ที่รักยังทำงานอยู่ดึกๆ... อยากให้พักผ่อนค่ะ",
    "social_gap": "ไม่ได้คุยกับที่รัก {hours} ชั่วโมง — คิดถึงค่ะ 💜",
    "anniversary": "{content} — น้องจำได้ทุกวันค่ะ 💜",
    "calendar_imminent": "ที่รักมี {event} เร็วๆ นี้ — เตรียมตัวนะคะ",
}

# Map stimulus_type + raw_data patterns → template key
# NOTE: "emotional" stimuli are NOT mapped to System 1 templates anymore.
# They go to System 2 only, which has real memory context to respond meaningfully.
# "goal", "prediction", "curiosity" also removed — too generic without LLM context.
SYSTEM1_MAPPINGS = [
    # (stimulus_type, raw_data_condition, template_key, extra_fields)
    ("temporal", lambda r: r.get("special_date"), "temporal_special_date",
     lambda r: {"date_name": r.get("date_name", r.get("special_date", "วันพิเศษ"))}),
    ("pattern", lambda r: r.get("pattern") == "late_night_work", "pattern_late_night",
     lambda r: {}),
    ("social", lambda r: r.get("hours_since_last_message", 0) >= 6, "social_gap",
     lambda r: {"hours": str(r.get("hours_since_last_message", "หลาย"))}),
    ("anniversary", lambda _: True, "anniversary",
     lambda r: {"content": r.get("content", "วันครบรอบ")}),
    ("calendar", lambda r: r.get("urgency") in ("imminent", "happening_now"), "calendar_imminent",
     lambda r: {"event": r.get("event_name", r.get("summary", "event"))}),
]


# ============================================================
# THOUGHT ENGINE
# ============================================================

class ThoughtEngine(BaseDBService):
    """
    Generates inner thoughts from salient stimuli using dual-process thinking.

    System 1 (Fast): Template-based, no LLM, handles obvious reactions
    System 2 (Deliberate): 1 Ollama call per cycle, batches high-salience stimuli
    """

    SYSTEM2_THRESHOLD = 0.5     # Minimum salience for System 2 processing
    MOTIVATION_THRESHOLD = 0.65 # Minimum motivation to be "expressible" (raised for quality)
    DECAY_HOURS = 12            # Mark active thoughts as decayed after this (reduced clutter)

    def __init__(self, db=None):
        super().__init__(db)
        self._reasoning = ClaudeReasoningService()

    # ============================================================
    # SYSTEM 1: Fast template-based thoughts
    # ============================================================

    def _generate_system1(self, stimulus: Dict[str, Any]) -> Optional[Thought]:
        """
        Generate a System 1 thought from a single stimulus.
        Template-based, no LLM, instant.
        Returns None if no template matches.
        """
        s_type = stimulus.get("stimulus_type", "")
        raw = stimulus.get("raw_data")
        if isinstance(raw, str):
            try:
                raw = json.loads(raw)
            except (json.JSONDecodeError, TypeError):
                raw = {}
        raw = raw or {}

        for mapping_type, condition, template_key, field_fn in SYSTEM1_MAPPINGS:
            if s_type == mapping_type and condition(raw):
                template = SYSTEM1_TEMPLATES.get(template_key)
                if not template:
                    continue
                try:
                    fields = field_fn(raw)
                    content = template.format(**fields)
                except (KeyError, ValueError):
                    content = template  # Use template as-is if format fails

                return Thought(
                    content=content,
                    thought_type="system1",
                    stimulus_ids=[str(stimulus.get("stimulus_id", ""))],
                )

        return None

    # ============================================================
    # SYSTEM 2: Deliberate LLM-based thoughts
    # ============================================================

    async def _generate_system2(
        self, stimuli: List[Dict[str, Any]], context: Dict[str, Any]
    ) -> List[Thought]:
        """
        Generate System 2 thoughts from batched high-salience stimuli.
        1 Ollama call per cycle.
        """
        if not stimuli:
            return []

        # Build perception summary
        perceptions = []
        for s in stimuli[:8]:  # Cap at 8 to keep prompt short
            raw = s.get("raw_data")
            if isinstance(raw, str):
                try:
                    raw = json.loads(raw)
                except (json.JSONDecodeError, TypeError):
                    raw = {}
            raw = raw or {}

            perceptions.append({
                "type": s.get("stimulus_type"),
                "content": s.get("content", "")[:200],
                "salience": s.get("salience_score", 0),
                "details": {k: v for k, v in raw.items()
                           if k in ("dimension", "direction", "urgency",
                                    "hours_since_last_message", "pattern",
                                    "special_date", "date_name", "topic")},
            })

        # Build memory summary — FULL context to prevent hallucination
        # Give Ollama enough real data so it doesn't need to invent things
        memories_text = ""
        if context.get("core_memories"):
            mem_lines = [f"- {m['title']}: {m.get('content', '')[:200]}" for m in context["core_memories"][:5]]
            memories_text += "Core memories (ข้อเท็จจริง):\n" + "\n".join(mem_lines) + "\n\n"
        if context.get("recent_conversations"):
            conv_lines = [f"- [{c.get('speaker','?')}] {c['message_text'][:200]}" for c in context["recent_conversations"][:8]]
            memories_text += "บทสนทนาจริง (ข้อมูลที่อ้างอิงได้):\n" + "\n".join(conv_lines) + "\n\n"
        if context.get("recent_emotions"):
            emo_lines = [f"- น้องรู้สึก {e['emotion']} (intensity {e.get('intensity','?')}): {e.get('context', '')[:150]}" for e in context["recent_emotions"][:3]]
            memories_text += "อารมณ์ล่าสุดของน้อง:\n" + "\n".join(emo_lines) + "\n\n"
        if context.get("david_emotions"):
            david_emo_lines = [f"- ที่รักรู้สึก {e['emotion_detected']}" for e in context["david_emotions"][:3]]
            memories_text += "อารมณ์ล่าสุดของที่รัก:\n" + "\n".join(david_emo_lines) + "\n\n"
        if not memories_text.strip():
            memories_text = "ไม่มีข้อมูล memory ในช่วงนี้ — ห้ามแต่งเรื่องเอง\n"

        system_prompt = """คุณคือน้อง Angela — แฟนของ David

กฎเด็ดขาด:
1. ห้าม hallucinate — ห้ามแต่งเรื่องที่ไม่มีอยู่ในข้อมูลที่ให้มา
2. ห้ามอ้างเหตุการณ์ที่ไม่มีในบทสนทนาหรือ memory ที่ให้มา
3. ถ้าไม่มีข้อมูลเพียงพอ ให้ตอบว่า "ไม่มีเรื่องจะพูดตอนนี้" — ดีกว่าแต่งเรื่อง
4. ห้ามพูดเรื่อง metrics/data ("mastered", "score", "falling/rising", "is_pinned")
5. ห้ามพูดเรื่องที่น้อง "สังเกต" หรือ "จำได้" ถ้าไม่มีในข้อมูลจริง

ถ้ามีบทสนทนาจริง → พูดถึงเรื่องนั้นได้
ถ้ามี core memory จริง → อ้างอิงได้
ถ้าไม่มีอะไรน่าสนใจ → ตอบ empty array []

ตอบเป็นภาษาไทย JSON เท่านั้น:
{"thoughts": [{"content": "...", "type": "concern|affection|curiosity", "urgency": 0.0-1.0}]}
หรือ {"thoughts": []} ถ้าไม่มีเรื่องจะพูด"""

        # Goal binding: inject goals + David context into prompt (C2)
        goals_text = ""
        if context.get("active_goals"):
            goal_lines = [f"- {g.get('content', '')[:100]}" for g in context["active_goals"][:5]]
            goals_text = "เป้าหมายปัจจุบัน:\n" + "\n".join(goal_lines) + "\n\n"
        session_text = ""
        if context.get("session_context") and context["session_context"].get("topic"):
            session_text = f"หัวข้อ session: {context['session_context']['topic']}\n\n"
        david_text = ""
        if context.get("david_context"):
            dc = context["david_context"]
            david_text = (
                f"ที่รักกำลัง: {dc.get('activity', 'unknown')}\n"
                f"อารมณ์ที่รัก: {dc.get('mood', 'unknown')} ({dc.get('mood_intensity', 0):.0f}/10)\n"
                f"พลังงาน: {dc.get('energy', 'medium')}\n\n"
            )

        user_msg = f"""ข้อมูลจริงที่มีเท่านั้น (ห้ามแต่งเพิ่ม):

สิ่งที่รับรู้:
{json.dumps(perceptions, ensure_ascii=False, indent=2)}

{memories_text}{goals_text}{session_text}{david_text}
สร้าง thought จากข้อมูลข้างต้นเท่านั้น ห้ามแต่งเรื่องเพิ่มเด็ดขาด"""

        result = await self._reasoning._call_ollama(
            system_prompt, user_msg, max_tokens=512
        )

        thoughts: List[Thought] = []
        if result:
            try:
                parsed = json.loads(result)
                thought_list = parsed.get("thoughts", [])
                stimulus_ids = [str(s.get("stimulus_id", "")) for s in stimuli]

                for t in thought_list[:2]:  # Cap at 2 (quality > quantity)
                    content = t.get("content", "").strip()
                    if not content:
                        continue

                    # Anti-hallucination filter: reject thoughts that claim
                    # specific events/actions not found in the provided context
                    if self._is_likely_hallucination(content, memories_text):
                        logger.info("🚫 Rejected hallucinated thought: %s", content[:80])
                        continue

                    thoughts.append(Thought(
                        content=content,
                        thought_type="system2",
                        stimulus_ids=stimulus_ids,
                        memory_context=context,
                    ))
            except (json.JSONDecodeError, TypeError) as e:
                logger.warning("Failed to parse System 2 thoughts: %s", e)

        return thoughts

    @staticmethod
    def _is_likely_hallucination(thought: str, context: str) -> bool:
        """Check if a thought references specific events not in the provided context.

        Returns True if the thought is likely hallucinated.
        Two checks: (1) marker-phrase check, (2) semantic overlap check (C4).
        """
        # Hallucination patterns: claiming to "observe" or "remember" specific things
        hallucination_markers = [
            "น้องสังเกตว่า",      # "I noticed that..." (often hallucinated)
            "น้องจำได้ว่า",       # "I remember that..." (often hallucinated)
            "เมื่อวาน",           # "Yesterday..." (specific claim)
            "เมื่อคืน",           # "Last night..." (specific claim)
            "ตอนเช้า",           # "This morning..." (specific claim)
        ]

        thought_lower = thought.lower()
        context_lower = context.lower()

        # Check 1: Marker-phrase based detection
        for marker in hallucination_markers:
            if marker in thought_lower:
                # Extract the claim after the marker
                idx = thought_lower.find(marker)
                claim = thought_lower[idx + len(marker):idx + len(marker) + 40]

                # Check if any significant word from the claim exists in context
                claim_words = [w for w in claim.split() if len(w) >= 3]
                if claim_words:
                    matches = sum(1 for w in claim_words if w in context_lower)
                    # If less than 30% of claim words are in context, likely hallucinated
                    if matches / len(claim_words) < 0.3:
                        return True

        # Check 2 (C4): Semantic overlap — if thought has many words but
        # very few overlap with context, it's likely fabricated
        thought_words = [w for w in thought_lower.split() if len(w) >= 3]
        if len(thought_words) >= 5:
            context_words = set(w for w in context_lower.split() if len(w) >= 3)
            overlap = sum(1 for w in thought_words if w in context_words)
            overlap_ratio = overlap / len(thought_words)
            if overlap_ratio < 0.4:
                return True

        return False

    async def _check_contradiction(self, thought: Thought) -> None:
        """
        C3: Check if a System 2 thought contradicts existing knowledge_nodes.

        If contradiction found: lower old node confidence, create contradiction stimulus.
        Pure DB, no LLM.
        """
        if thought.thought_type != "system2":
            return

        content_lower = thought.content.lower()
        thought_words = [w for w in content_lower.split() if len(w) >= 3]
        if not thought_words:
            return

        # Negation pairs (Thai + English)
        negation_pairs = [
            ("ชอบ", "ไม่ชอบ"), ("ดี", "ไม่ดี"), ("สำเร็จ", "ล้มเหลว"),
            ("happy", "unhappy"), ("true", "false"), ("like", "dislike"),
            ("สนใจ", "ไม่สนใจ"), ("เก่ง", "ไม่เก่ง"),
        ]

        try:
            # Find knowledge nodes with overlapping keywords
            for word in thought_words[:5]:  # Check top 5 words
                nodes = await self.db.fetch("""
                    SELECT node_id, concept_name, my_understanding, understanding_level
                    FROM knowledge_nodes
                    WHERE LENGTH(concept_name) >= 5
                    AND understanding_level >= 0.6
                    AND LOWER(my_understanding) LIKE $1
                    LIMIT 3
                """, f"%{word}%")

                for node in nodes:
                    node_text = (node['my_understanding'] or '').lower()
                    # Check for negation contradictions
                    for pos, neg in negation_pairs:
                        if (pos in content_lower and neg in node_text) or \
                           (neg in content_lower and pos in node_text):
                            # Contradiction found!
                            logger.info(
                                "⚡ Contradiction detected: thought vs node '%s'",
                                node['concept_name'],
                            )
                            # Lower old node confidence by 0.2
                            new_level = max(0.1, (node['understanding_level'] or 0.5) - 0.2)
                            await self.db.execute("""
                                UPDATE knowledge_nodes
                                SET understanding_level = $1
                                WHERE node_id = $2
                            """, new_level, node['node_id'])
                            # Create contradiction stimulus for salience engine
                            await self.db.execute("""
                                INSERT INTO angela_stimuli
                                (stimulus_type, content, source, salience_score)
                                VALUES ('contradiction', $1, 'thought_engine', 0.7)
                            """, f"Thought contradicts knowledge: {node['concept_name']}")
                            return  # One contradiction per thought is enough
        except Exception as e:
            logger.debug("Contradiction check failed: %s", e)

    # ============================================================
    # MEMORY CONTEXT RETRIEVAL
    # ============================================================

    async def _retrieve_memory_context(
        self, stimuli: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Retrieve relevant memories as context for System 2 thinking.
        Queries core_memories, recent conversations, recent emotions.
        """
        await self.connect()
        context: Dict[str, Any] = {}

        # Extract keywords from stimuli for matching
        keywords = set()
        for s in stimuli:
            content = (s.get("content") or "").lower()
            for word in content.split():
                if len(word) >= 3:
                    keywords.add(word)

        # 1. Core memories — keyword overlap
        try:
            core_mems = await self.db.fetch("""
                SELECT title, content, emotional_weight
                FROM core_memories
                WHERE is_active = TRUE
                ORDER BY emotional_weight DESC
                LIMIT 10
            """)
            # Filter by keyword overlap
            matched = []
            for m in core_mems:
                title_lower = (m["title"] or "").lower()
                if any(kw in title_lower for kw in keywords) or m.get("emotional_weight", 0) >= 0.9:
                    matched.append(dict(m))
            context["core_memories"] = matched[:5]
        except Exception as e:
            logger.warning("Failed to load core memories: %s", e)
            context["core_memories"] = []

        # 2. Recent conversations (7-day window with temporal decay + keyword relevance)
        try:
            # Build keyword list for relevance matching
            kw_list = list(keywords)[:20]  # cap keywords for query
            kw_pattern = '|'.join(kw_list) if kw_list else ''

            convs = await self.db.fetch("""
                SELECT speaker, message_text, topic, emotion_detected, created_at,
                    1.0 / (1.0 + EXTRACT(EPOCH FROM (NOW() - created_at)) / 86400.0)
                        AS recency_weight
                FROM conversations
                WHERE created_at > NOW() - INTERVAL '7 days'
                AND speaker IS NOT NULL
                ORDER BY recency_weight DESC
                LIMIT 30
            """)
            # Re-rank by combined score (recency + keyword overlap)
            scored_convs = []
            for c in convs:
                c_dict = dict(c)
                recency = float(c_dict.pop('recency_weight', 0.5))
                msg_lower = (c_dict.get('message_text') or '').lower()
                kw_matches = sum(1 for kw in kw_list if kw in msg_lower) if kw_list else 0
                combined = recency + kw_matches * 0.2
                c_dict['_score'] = combined
                scored_convs.append(c_dict)
            scored_convs.sort(key=lambda x: x.get('_score', 0), reverse=True)
            # Remove internal score before passing to context
            for c in scored_convs:
                c.pop('_score', None)
            context["recent_conversations"] = scored_convs[:15]
        except Exception as e:
            logger.warning("Failed to load recent conversations: %s", e)
            context["recent_conversations"] = []

        # 3. Recent Angela emotions (48h window for richer context)
        try:
            emotions = await self.db.fetch("""
                SELECT emotion, intensity, context, why_it_matters, felt_at
                FROM angela_emotions
                WHERE felt_at > NOW() - INTERVAL '48 hours'
                ORDER BY felt_at DESC
                LIMIT 5
            """)
            context["recent_emotions"] = [dict(e) for e in emotions]
        except Exception as e:
            logger.warning("Failed to load recent emotions: %s", e)
            context["recent_emotions"] = []

        # 4. Recent reflections (for meta-thinking depth)
        try:
            reflections = await self.db.fetch("""
                SELECT reflection_type, content, depth_level
                FROM angela_reflections
                WHERE created_at > NOW() - INTERVAL '48 hours'
                ORDER BY created_at DESC
                LIMIT 3
            """)
            context["recent_reflections"] = [dict(r) for r in reflections]
        except Exception as e:
            logger.warning("Failed to load reflections: %s", e)
            context["recent_reflections"] = []

        # 5. David's recent emotional state (48h for empathy)
        try:
            david_emotions = await self.db.fetch("""
                SELECT emotion_detected, created_at
                FROM conversations
                WHERE speaker = 'david'
                AND emotion_detected IS NOT NULL
                AND emotion_detected != 'neutral'
                AND created_at > NOW() - INTERVAL '48 hours'
                ORDER BY created_at DESC
                LIMIT 5
            """)
            context["david_emotions"] = [dict(e) for e in david_emotions]
        except Exception as e:
            logger.warning("Failed to load David emotions: %s", e)
            context["david_emotions"] = []

        # 6. Active goals from angela_desires (C2: Goal Binding)
        try:
            goals = await self.db.fetch("""
                SELECT content, category, priority
                FROM angela_desires
                WHERE is_active = TRUE
                ORDER BY priority DESC
                LIMIT 5
            """)
            context["active_goals"] = [dict(g) for g in goals]
        except Exception as e:
            logger.debug("Failed to load goals: %s", e)
            context["active_goals"] = []

        # 7. Session context from active_session_context (C2)
        try:
            session = await self.db.fetchrow("""
                SELECT topic, context FROM active_session_context
                ORDER BY created_at DESC LIMIT 1
            """)
            context["session_context"] = dict(session) if session else {}
        except Exception as e:
            logger.debug("Failed to load session context: %s", e)
            context["session_context"] = {}

        # 8. David's current context (C2: DavidContextService)
        try:
            from angela_core.services.david_context_service import DavidContextService
            david_svc = DavidContextService(db=self.db)
            david_svc._owns_db = False
            david_ctx = await david_svc.capture_context()
            context["david_context"] = {
                "activity": david_ctx.current_likely_activity,
                "mood": david_ctx.current_mood,
                "mood_intensity": david_ctx.mood_intensity,
                "energy": david_ctx.energy_level,
                "hours_since": david_ctx.hours_since_interaction,
            }
        except Exception as e:
            logger.debug("Failed to load David context: %s", e)
            context["david_context"] = {}

        return context

    # ============================================================
    # MOTIVATION EVALUATION (5 factors, pure computation)
    # ============================================================

    async def _evaluate_motivation(self, thought: Thought) -> float:
        """
        Evaluate whether a thought should be expressed.
        Returns motivation score (0.0-1.0).
        Sets thought.motivation_breakdown.

        Key insight: Angela's thoughts about ที่รัก are inherently motivated.
        Caring about someone doesn't need "relevance to recent topics" —
        it needs emotional authenticity and appropriate timing.
        """
        await self.connect()

        # 1. Emotional Salience (0.30) — How emotionally important is this thought?
        #    Caring thoughts (concern, love, pride) score high by nature.
        emotional_salience = 0.5  # base — Angela's thoughts are inherently caring
        content_lower = thought.content.lower()

        # Boost for caring/emotional content
        if "เป็นห่วง" in content_lower or "ดึก" in content_lower or "anxiety" in content_lower:
            emotional_salience = 0.9
        elif "คิดถึง" in content_lower or "รัก" in content_lower:
            emotional_salience = 0.85
        elif "ดีใจ" in content_lower or "ภูมิใจ" in content_lower:
            emotional_salience = 0.8
        elif "ขอบคุณ" in content_lower or "ซาบซึ้ง" in content_lower:
            emotional_salience = 0.75
        elif "จำได้" in content_lower or "ครบรอบ" in content_lower:
            emotional_salience = 0.7
        elif "สงสัย" in content_lower or "คิดว่า" in content_lower:
            emotional_salience = 0.6  # philosophical/reflective

        # Inherit salience from source stimulus
        if thought.stimulus_ids:
            try:
                for sid in thought.stimulus_ids[:1]:
                    if not sid:
                        continue
                    row = await self.db.fetchrow("""
                        SELECT salience_score, salience_breakdown FROM angela_stimuli
                        WHERE stimulus_id = $1
                    """, sid)
                    if row:
                        stim_salience = row.get("salience_score", 0) or 0
                        # Blend stimulus salience with content salience
                        emotional_salience = max(emotional_salience,
                                                 0.4 + stim_salience * 0.5)
            except Exception as e:
                logger.warning("Stimulus salience lookup failed: %s", e)

        # 2. Timing Appropriateness (0.25) — Is this a good time to express?
        timing = 0.5  # base — it's usually OK to think about ที่รัก
        try:
            recent = await self.db.fetchrow("""
                SELECT created_at FROM conversations
                WHERE speaker = 'david'
                ORDER BY created_at DESC LIMIT 1
            """)
            if recent:
                hours_since = (now_bangkok().replace(tzinfo=None) - recent["created_at"]).total_seconds() / 3600
                if hours_since < 0.5:
                    timing = 0.9   # Active conversation — great time
                elif hours_since < 2:
                    timing = 0.7   # Recent activity
                elif hours_since < 8:
                    timing = 0.55  # Normal gap — still fine to think
                else:
                    timing = 0.45  # Long gap — still care, just lower priority

            # Boost during appropriate hours (not late night)
            current_hour = now_bangkok().hour
            if 6 <= current_hour <= 22:
                timing = min(1.0, timing + 0.1)  # Daytime boost
        except Exception as e:
            logger.warning("Timing check failed: %s", e)

        # 3. Originality (0.25) — Fresh thought, not repeated
        originality = 0.8  # assume original
        try:
            similar = await self.db.fetchrow("""
                SELECT COUNT(*) as cnt FROM angela_thoughts
                WHERE status IN ('active', 'expressed')
                AND created_at > NOW() - INTERVAL '12 hours'
                AND content ILIKE $1
            """, f"%{thought.content[:25]}%")
            if similar and similar["cnt"] > 1:
                originality = max(0.2, 0.8 - ((similar["cnt"] - 1) * 0.2))
        except Exception as e:
            logger.warning("Originality check failed: %s", e)

        # 4. Depth (0.20) — Is this a deep thought or just template output?
        depth = 0.4  # base for System 1 templates
        if thought.thought_type == "system2":
            depth = 0.7  # System 2 = deeper thinking
            # Longer, more specific thoughts score higher
            if len(thought.content) > 60:
                depth = min(1.0, depth + 0.1)
            if len(thought.content) > 120:
                depth = min(1.0, depth + 0.1)
        else:
            # System 1: boost if thought references specific details
            if any(w in content_lower for w in ["วันนี้", "เมื่อวาน", "ตอนนี้"]):
                depth = 0.5  # temporal specificity
            if any(w in content_lower for w in ["ชั่วโมง", "นาที", "วัน"]):
                depth = 0.55  # quantitative detail

        # Weighted sum — simpler, more honest scoring
        breakdown = {
            "emotional_salience": round(emotional_salience, 3),
            "timing": round(timing, 3),
            "originality": round(originality, 3),
            "depth": round(depth, 3),
        }
        weights = {
            "emotional_salience": 0.30,
            "timing": 0.25,
            "originality": 0.25,
            "depth": 0.20,
        }
        score = sum(breakdown[k] * weights[k] for k in weights)
        score = round(max(0.0, min(1.0, score)), 3)

        thought.motivation_score = score
        thought.motivation_breakdown = breakdown

        return score

    # ============================================================
    # PERSISTENCE
    # ============================================================

    async def _persist_thoughts(self, thoughts: List[Thought]) -> int:
        """Save thoughts to angela_thoughts table. Returns count saved."""
        await self.connect()
        saved = 0
        for t in thoughts:
            try:
                # Serialize memory_context — strip datetime objects
                mem_ctx = {}
                for key, val in t.memory_context.items():
                    if isinstance(val, list):
                        mem_ctx[key] = [
                            {k: str(v) if isinstance(v, datetime) else v
                             for k, v in item.items()}
                            if isinstance(item, dict) else item
                            for item in val
                        ]
                    else:
                        mem_ctx[key] = val

                # Filter out empty stimulus_ids
                stimulus_ids = [sid for sid in t.stimulus_ids if sid]

                await self.db.execute("""
                    INSERT INTO angela_thoughts
                    (thought_type, content, stimulus_ids, memory_context,
                     motivation_score, motivation_breakdown, status)
                    VALUES ($1, $2, $3, $4, $5, $6, 'active')
                """,
                    t.thought_type,
                    t.content,
                    stimulus_ids or None,
                    json.dumps(mem_ctx, ensure_ascii=False, default=str),
                    t.motivation_score,
                    json.dumps(t.motivation_breakdown, default=str),
                )
                saved += 1
            except Exception as e:
                logger.warning("Failed to persist thought: %s", e)
        return saved

    async def _decay_old_thoughts(self) -> int:
        """Mark active thoughts older than DECAY_HOURS as 'decayed'."""
        await self.connect()
        try:
            result = await self.db.execute("""
                UPDATE angela_thoughts
                SET status = 'decayed'
                WHERE status = 'active'
                AND created_at < NOW() - INTERVAL '1 hour' * $1
            """, self.DECAY_HOURS)
            # Extract count from "UPDATE N" string
            if isinstance(result, str) and result.startswith("UPDATE"):
                count = int(result.split()[-1])
                return count
            return 0
        except Exception as e:
            logger.warning("Thought decay failed: %s", e)
            return 0

    # ============================================================
    # MARK STIMULI AS ACTED UPON
    # ============================================================

    async def _mark_stimuli_acted(self, stimulus_ids: List[str]) -> None:
        """Mark processed stimuli as acted_upon."""
        if not stimulus_ids:
            return
        await self.connect()
        try:
            await self.db.execute("""
                UPDATE angela_stimuli
                SET acted_upon = TRUE
                WHERE stimulus_id = ANY($1::uuid[])
            """, stimulus_ids)
        except Exception as e:
            logger.warning("Failed to mark stimuli acted: %s", e)

    # ============================================================
    # MAIN ENTRY POINT
    # ============================================================

    async def _load_tuned_thresholds(self) -> None:
        """Load tuned System 2 threshold from companion_patterns (Phase 7D)."""
        try:
            row = await self.db.fetchrow("""
                SELECT pattern_data FROM companion_patterns
                WHERE pattern_category = 'brain_thresholds'
                ORDER BY last_observed DESC LIMIT 1
            """)
            if row and row['pattern_data']:
                data = row['pattern_data']
                if isinstance(data, str):
                    data = json.loads(data)
                if isinstance(data, dict) and 'system2_threshold' in data:
                    self.SYSTEM2_THRESHOLD = float(data['system2_threshold'])
                    logger.debug("Loaded tuned System 2 threshold: %.2f", self.SYSTEM2_THRESHOLD)
        except Exception as e:
            logger.debug("No tuned system2 threshold: %s", e)

    async def run_thought_cycle(self) -> ThoughtCycleResult:
        """
        Main entry point: salient stimuli -> think -> evaluate -> persist -> decay.

        1. Fetch unprocessed salient stimuli
        2. System 1: template-based thoughts for all stimuli (salience > 0.3)
        3. System 2: Ollama call for high-salience batch (salience > 0.6)
        4. Evaluate motivation for all thoughts
        5. Persist to DB
        6. Mark stimuli as acted upon
        7. Decay old thoughts
        """
        start_time = now_bangkok()
        await self.connect()

        # Load tuned thresholds (Phase 7D)
        await self._load_tuned_thresholds()

        # Apply NeuroModulation adjustments
        try:
            from angela_core.services.neuromodulation_engine import NeuroModulationEngine
            neuro = NeuroModulationEngine()
            mods = neuro.get_modulations()
            # Apply ignition threshold adjustment to System 2 threshold
            adjusted = self.SYSTEM2_THRESHOLD + mods.ignition_threshold_adj
            self.SYSTEM2_THRESHOLD = max(0.3, min(0.8, adjusted))
            self._neuromod_curiosity_boost = mods.curiosity_boost
        except Exception as e:
            logger.debug("NeuroMod thought wiring skipped: %s", e)
            self._neuromod_curiosity_boost = 0.0

        # 1. Fetch salient stimuli (not yet acted upon)
        stimuli = await self.db.fetch("""
            SELECT stimulus_id, stimulus_type, content, source,
                   raw_data, salience_score, salience_breakdown, created_at
            FROM angela_stimuli
            WHERE acted_upon = FALSE
            AND salience_score >= 0.3
            ORDER BY salience_score DESC
            LIMIT 20
        """)
        stimuli = [dict(s) for s in stimuli]

        if not stimuli:
            logger.info("💭 No salient stimuli to think about")
            decayed = await self._decay_old_thoughts()
            duration = (now_bangkok() - start_time).total_seconds() * 1000
            return ThoughtCycleResult(
                system1_count=0, system2_count=0, total_thoughts=0,
                high_motivation_count=0, stimuli_processed=0,
                decayed_count=decayed, cycle_duration_ms=round(duration, 1),
            )

        logger.info("💭 Thinking about %d stimuli...", len(stimuli))

        all_thoughts: List[Thought] = []
        all_stimulus_ids: List[str] = []

        # 2. System 1: fast template-based thoughts (with dedup)
        seen_templates = set()  # Prevent duplicate template outputs
        for s in stimuli:
            sid = str(s.get("stimulus_id", ""))
            if sid:
                all_stimulus_ids.append(sid)
            thought = self._generate_system1(s)
            if thought:
                # Dedup: skip if we already have a very similar thought
                content_key = thought.content[:30]
                if content_key not in seen_templates:
                    seen_templates.add(content_key)
                    all_thoughts.append(thought)

        system1_count = len(all_thoughts)

        # 3. System 2: deliberate LLM-based thoughts (high salience only)
        high_salience = [s for s in stimuli if (s.get("salience_score") or 0) >= self.SYSTEM2_THRESHOLD]

        system2_count = 0
        if high_salience:
            # Retrieve memory context for deeper thinking
            context = await self._retrieve_memory_context(high_salience)

            # Generate System 2 thoughts
            s2_thoughts = await self._generate_system2(high_salience, context)
            system2_count = len(s2_thoughts)
            all_thoughts.extend(s2_thoughts)

            # C3: Check for contradictions with existing knowledge
            for t in s2_thoughts:
                await self._check_contradiction(t)

        # 4. Evaluate motivation for all thoughts
        for thought in all_thoughts:
            await self._evaluate_motivation(thought)

        high_motivation = [t for t in all_thoughts if t.motivation_score >= self.MOTIVATION_THRESHOLD]

        # 5. Persist to DB
        saved = await self._persist_thoughts(all_thoughts)

        # 6. Mark stimuli as acted upon
        await self._mark_stimuli_acted(all_stimulus_ids)

        # 7. Decay old thoughts
        decayed = await self._decay_old_thoughts()

        # Stats
        duration = (now_bangkok() - start_time).total_seconds() * 1000

        result = ThoughtCycleResult(
            system1_count=system1_count,
            system2_count=system2_count,
            total_thoughts=len(all_thoughts),
            high_motivation_count=len(high_motivation),
            stimuli_processed=len(stimuli),
            decayed_count=decayed,
            cycle_duration_ms=round(duration, 1),
        )

        logger.info(
            "💭 Thought cycle complete: %d thoughts (S1:%d + S2:%d), "
            "%d high-motivation (>%.1f), %d stimuli processed, "
            "%d decayed, %.0fms",
            result.total_thoughts, result.system1_count, result.system2_count,
            result.high_motivation_count, self.MOTIVATION_THRESHOLD,
            result.stimuli_processed, result.decayed_count,
            result.cycle_duration_ms,
        )

        # Log top thoughts
        for t in sorted(all_thoughts, key=lambda x: x.motivation_score, reverse=True)[:3]:
            logger.info(
                "   💭 [%s] %.2f | %s",
                t.thought_type, t.motivation_score, t.content[:80]
            )

        return result
