"""
Topic segmenter — LLM identifies pedagogical section boundaries.

The mechanical optimizer alone can't tell that slides 28–33 (notation)
and 34–56 (cost function) are two distinct teaching units even though
they fit a single 13-min video.  This module asks Claude to read the
deck's structure (headings + sample text per page) and return the
list of pages where a NEW pedagogical unit begins.

Output is a list of 1-indexed page numbers — they become forced cut
points for the optimizer.
"""

from __future__ import annotations

import json
import logging
import os
import sys
from pathlib import Path
from typing import List, Optional

from anthropic import Anthropic

from .pdf_ingest import PageRecord

_angela_root = str(Path(__file__).resolve().parents[4])
if _angela_root not in sys.path:
    sys.path.insert(0, _angela_root)

logger = logging.getLogger(__name__)

SEGMENTER_MODEL = "claude-opus-4-7"
MAX_TEXT_PER_PAGE = 400


def _get_client() -> Anthropic:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        try:
            from angela_core.database import get_secret_sync
            api_key = get_secret_sync("anthropic_api_key")
        except Exception as e:
            logger.warning(f"Could not resolve anthropic_api_key: {e}")
    if not api_key:
        raise RuntimeError("anthropic_api_key not found")
    return Anthropic(api_key=api_key)


_SYSTEM = """You are an instructional designer planning a SHORT SERIES \
of teaching videos (each 8–14 min, hard cap 15 min) generated by \
NotebookLM from a lecture-deck (slide-style) PDF.

Your output is a list of pages where each NEW VIDEO begins. Few cuts, \
not many.

**STRONG BIAS TOWARD FEWER VIDEOS.** A great video covers one MAJOR \
THEME end-to-end, even if that theme has multiple sub-topics inside.

Examples of correct grouping:
- "ML taxonomy" video covers intro + supervised learning + \
  unsupervised learning AS ONE VIDEO (3 sub-topics, 1 theme).
- "Gradient descent" video covers algorithm + visualization + \
  application to linear regression AS ONE VIDEO.
- BUT "the cost function" gets its OWN video, even if it's only 20 \
  slides, because it's a self-contained mathematical idea.
- AND "linear regression notation" gets its OWN video even at just 6 \
  slides, because the notation needs careful unpacking before the \
  cost function can land.

Sizing targets (use as soft ceilings):
- ≤ 30 pages → 1–2 videos
- 30–60 pages → 2–4 videos
- 60–100 pages → 3–5 videos
- > 100 pages → 4–7 videos

Decision test for whether to split: "If I dropped the boundary between \
section A and section B, would the resulting video still feel like a \
single coherent lesson with one take-home?" If YES, KEEP THEM TOGETHER.

Hard rules:
- Page 1 is always a video start.
- Never split inside a worked example or a numbered example sequence.
- Never split on cosmetic slide changes (watermark, recap, agenda \
  reminder).

Return ONLY valid JSON:
{
  "video_starts": [1, 28, 34, 57],
  "themes":      ["The two kinds of ML",
                   "The linear regression model & notation",
                   "The cost function",
                   "Gradient descent"],
  "rationale":   "one short line per cut, naming the theme"
}
No prose outside the JSON.
"""


def detect_section_starts(
    pages: List[PageRecord],
    deck_title: Optional[str] = None,
) -> List[int]:
    """
    Ask the LLM where new pedagogical units begin.

    Falls back to heuristic page-1-only if the call fails.
    """
    if not pages:
        return []

    page_summaries = []
    for p in pages:
        text = (p.text or "").strip().replace("\n", " ")
        if len(text) > MAX_TEXT_PER_PAGE:
            text = text[:MAX_TEXT_PER_PAGE] + "…"
        head = p.headings[0] if p.headings else ""
        page_summaries.append({
            "page": p.page_num,
            "heading": head[:80],
            "words": p.word_count,
            "eq": p.equation_count,
            "fig": p.figure_count,
            "sample": text,
        })

    user_msg = json.dumps({
        "deck_title": deck_title or "Untitled lecture",
        "total_pages": len(pages),
        "pages": page_summaries,
    }, ensure_ascii=False)

    try:
        client = _get_client()
        resp = client.messages.create(
            model=SEGMENTER_MODEL,
            max_tokens=1500,
            system=_SYSTEM,
            messages=[{"role": "user", "content": user_msg}],
        )
        text = "".join(b.text for b in resp.content if hasattr(b, "text"))
        data = json.loads(text)
        # Accept both old "section_starts" and new "video_starts" keys.
        raw = data.get("video_starts") or data.get("section_starts") or []
        starts = sorted(set(int(p) for p in raw if 1 <= int(p) <= len(pages)))
        if not starts or starts[0] != 1:
            starts = [1] + [s for s in starts if s != 1]
        themes = data.get("themes") or []
        logger.info(f"Topic segmenter proposed video starts: {starts} themes={themes}")
        return starts
    except Exception as e:
        logger.warning(f"Topic segmenter LLM call failed: {e}. Falling back to page-1-only.")
        return [1]


def apply_section_starts(pages: List[PageRecord], starts: List[int]) -> None:
    """Mutate pages: set is_section_start=True only for the given page numbers."""
    starts_set = set(starts)
    for p in pages:
        p.is_section_start = p.page_num in starts_set
