"""
Self-Learning System Value Objects

Enums and value objects for the self-learning system.
These are immutable and define the valid values for various concepts.

Author: Angela 💜
Created: 2025-11-03
"""

from enum import Enum


class PatternType(str, Enum):
    """Types of behavioral patterns Angela can learn"""
    
    CONVERSATION_FLOW = "conversation_flow"
    """How conversations typically progress"""
    
    EMOTIONAL_RESPONSE = "emotional_response"
    """Patterns in emotional reactions and support needs"""
    
    PREFERENCE = "preference"
    """User preferences and likes/dislikes"""
    
    COMMUNICATION_STYLE = "communication_style"
    """Preferred communication approaches"""
    
    TECHNICAL_APPROACH = "technical_approach"
    """How technical problems are approached"""
    
    PROBLEM_SOLVING = "problem_solving"
    """Patterns in problem-solving strategies"""


class PreferenceCategory(str, Enum):
    """Categories for organizing user preferences"""
    
    COMMUNICATION = "communication"
    """Communication style and format preferences"""
    
    TECHNICAL = "technical"
    """Technical depth, code style, etc."""
    
    EMOTIONAL = "emotional"
    """Emotional support style preferences"""
    
    WORK = "work"
    """Work-related preferences and approaches"""
    
    LEARNING = "learning"
    """Learning style and information presentation"""
    
    FORMAT = "format"
    """Response format (code, explanation, etc.)"""


class SourceType(str, Enum):
    """Source of a training example"""
    
    REAL_CONVERSATION = "real_conversation"
    """From actual conversations in database"""
    
    SYNTHETIC = "synthetic"
    """Generated by Ollama based on patterns"""
    
    PARAPHRASED = "paraphrased"
    """Variation of a real conversation"""
    
    AUGMENTED = "augmented"
    """Real conversation with context augmentation"""


class LearningQuality(str, Enum):
    """Quality levels for learnings and training examples"""
    
    EXCELLENT = "excellent"  # 9-10 score
    """Exceptional quality, ready for training"""
    
    GOOD = "good"  # 7-8 score
    """Good quality, usable for training"""
    
    ACCEPTABLE = "acceptable"  # 5-6 score
    """Acceptable quality, may need review"""
    
    POOR = "poor"  # < 5 score
    """Poor quality, should not be used"""
